object_detection:
  ros__parameters:
    input_img_topic: color_camera/image_raw
    output_bb_topic: object_detection/img_bb
    output_img_topic: object_detection/img
    model_params:
      detector_type: YOLOv8
      model_dir_path: model/yolov8
      weight_file_name: version5.pt