object_detection:
  ros__parameters:
    input_img_topic: color_camera/image_raw
    output_bb_topic: object_detection/img_bb
    output_img_topic: object_detection/img
    model_params:
      detector_type: RetinaNet
      model_dir_path: models/retinanet
      weight_file_name: retinanet.h5
      confidence_threshold : 0.7
      show_fps : 1