name: Build and Test Workflows

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  build_source:
    name: Build Docker Image and ROS 2 Packages
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run:  docker build . --file Dockerfile.ubuntu -t ${{ github.repository }}:latest
      - name: Run Docker Image
        run:  docker run --name perception_pipeline -v ${{ github.workspace }}:/root/percep_ws/src ${{ github.repository }}:latest
      - name: Attach the docker container
        run:  docker attach perception_pipeline
      - name: Build ROS 2 Packages
        run:  colcon build
